use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ErrorCode {
    AlreadyInitialized = 100,
    NotAuthorized = 101,
    MarketNotFound = 102,
    MarketClosed = 103,
    MarketStillActive = 104,
    InvalidOutcome = 105,
    InvalidBetAmount = 106,
    InsufficientBalance = 107,
    OracleFailure = 108,
    CircuitBreakerOpen = 109,
    DisputeWindowClosed = 110,
    VotingNotStarted = 111,
    VotingEnded = 112,
    AlreadyVoted = 113,
    FeeTooHigh = 114,
    MarketNotActive = 115,
    DeadlinePassed = 116,
    CannotChangeOutcome = 117,
    MarketNotDisputed = 118,
    MarketNotPendingResolution = 119,
    AdminNotSet = 120,
    ContractPaused = 121,
    GuardianNotSet = 122,
    TooManyOutcomes = 123,
    TooManyWinners = 124,
    PayoutModeNotSupported = 125,
    InsufficientDeposit = 126,
    TimelockActive = 127,
    UpgradeNotInitiated = 128,
    InsufficientVotes = 129,
    AlreadyVotedOnUpgrade = 130,
    InvalidWasmHash = 131,
    UpgradeFailed = 132,
    ParentMarketNotResolved = 133,
    ParentMarketInvalidOutcome = 134,
    InsufficientVotingWeight = 135,
    MarketNotCancelled = 136,
    BetNotFound = 137,
    ResolutionNotReady = 138,
    StalePrice = 139,
    ConfidenceTooLow = 140,
    DisputeWindowStillOpen = 141,
    NoMajorityReached = 142,
    AssetClawedBack = 143,
    GovernanceTokenNotSet = 144,
    InvalidAmount = 145,
    NoWinnings = 146,
    MarketNotResolved = 147,
    AlreadyClaimed = 148,
    GracePeriodActive = 150,
    InvalidDeadline = 151,
    // Additional variants
    InvalidAmount = 135,
    InvalidDeadline = 136,
    InvalidReferrer = 137,
    NoWinnings = 138,
    AlreadyClaimed = 139,
    MarketNotResolved = 140,
    GracePeriodActive = 141,
    BetNotFound = 142,
    ResolutionNotReady = 143,
    DisputeWindowStillOpen = 144,
    NoMajorityReached = 145,
    StalePrice = 146,
    ConfidenceTooLow = 147,
    GovernanceTokenNotSet = 148,
    InsufficientVotingWeight = 149,
    ResolutionDeadlinePassed = 150,
}
